spring:
    profiles:
        active:
        - dev
---
spring:
    profiles:
    application:
        name: microserviceclod-config-gdie-dev
---
spring:
    profiles:
    application:
        name: microserviceclod-config-gdie-test
# 用UTF-8保存